version: '3'

services:

  # DJANGO
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: djangoTEST
    # restart: unless-stopped
    tty: true
    working_dir: /code
    ports:
      - "8000:8000"
    volumes:
      - ./:/code
    networks:
      - app-network

  #REDIS
  redis:
    image: redis:5.0.7
    container_name: redisDjangoTEST
    tty: true
    volumes:
      - redistest:/data
    networks:
      - app-network

  #POSTGRES
  postgres:
    image: postgres:12.1-alpine
    container_name: postgresdjangoTEST
    restart: always
    environment:
      POSTGRES_PASSWORD: hola123
      POSTGRES_USER: django
      POSTGRES_DB: test_drf
    tty: true
    volumes:
      - dbdatatest:/var/lib/postgresql/data
    ports:
      - "54320:5432"
    networks:
      - app-network

#CONFIGURATION
networks:
  app-network:
    driver: bridge

volumes:
  dbdatatest:
  redistest:

volumes:
  dbdatatest:
    driver: local
  redistest:
    driver: local